# Generated by Django 4.0.2 on 2022-04-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
